---DESDE APEX UN PROCESO ON SUBMIT
DECLARE
 	V_MENSAJE_RESULTADO VARCHAR2(500);
 	V_EMPLOYEE_ID INTEGER;
    V_CODIGO_RESULTADO INTEGER;
BEGIN
	HR.P_AGREGAR_EMPLEADO(
	    P_EMPLOYEE_ID => V_EMPLOYEE_ID,
	    P_MENSAJE_RESULTADO => V_MENSAJE_RESULTADO,
        P_CODIGO_RESULTADO => V_CODIGO_RESULTADO,
		P_FIRST_NAME => :P8_FIRST_NAME,
		P_LAST_NAME => :P8_LAST_NAME,
		P_EMAIL => :P8_EMAIL,
		P_PHONE_NUMBER => :P8_PHONE_NUMBER,
		P_HIRE_DATE=> :P8_HIRE_DATE,
		P_JOB_ID=> :P8_JOB_ID,
		P_SALARY=> :P8_SALARY,
		P_COMMISSION_PCT=> :P8_COMMISSION_PCT,
		P_MANAGER_ID=> :P8_MANAGER_ID,
		P_DEPARTMENT_ID=>:P8_DEPARTMENT_ID
	);

	:P8_EMPLOYEE_ID := V_EMPLOYEE_ID;
END;


--DESDE EL ESQUEMA CREAR EL PROCEDIMIENTO
CREATE OR REPLACE PROCEDURE P_AGREGAR_EMPLEADO(
    P_EMPLOYEE_ID OUT INTEGER,
    P_MENSAJE_RESULTADO OUT VARCHAR2,
    P_CODIGO_RESULTADO OUT INTEGER,
    P_FIRST_NAME VARCHAR2,
    P_LAST_NAME VARCHAR2,
    P_EMAIL VARCHAR2,
    P_PHONE_NUMBER VARCHAR2,
    P_HIRE_DATE DATE,
    P_JOB_ID VARCHAR2,
    P_SALARY NUMBER,
    P_COMMISSION_PCT NUMBER,
    P_MANAGER_ID INTEGER,
    P_DEPARTMENT_ID INTEGER
) AS
BEGIN
    P_EMPLOYEE_ID := EMPLOYEES_SEQ.NEXTVAL;
    INSERT INTO EMPLOYEES
      (
        EMPLOYEE_ID,
        FIRST_NAME,
        LAST_NAME,
        EMAIL,
        PHONE_NUMBER,
        HIRE_DATE,
        JOB_ID,
        SALARY,
        COMMISSION_PCT,
        MANAGER_ID,
        DEPARTMENT_ID
      )
      VALUES
      (
        P_EMPLOYEE_ID,
        P_FIRST_NAME,
        P_LAST_NAME,
        P_EMAIL,
        P_PHONE_NUMBER,
        P_HIRE_DATE,
        P_JOB_ID,
        P_SALARY,
        P_COMMISSION_PCT,
        P_MANAGER_ID,
        P_DEPARTMENT_ID
      );
      COMMIT;
      P_MENSAJE_RESULTADO := 'REGISTRO INSERTADO';
      P_CODIGO_RESULTADO := 0;
EXCEPTION
  WHEN OTHERS THEN
      P_MENSAJE_RESULTADO := 'ERROR AL INSERTAR, ERROR:'||SQLERRM;
      P_CODIGO_RESULTADO := SQLCODE;
      ROLLBACK;
END;