CREATE OR REPLACE VIEW VW_DETALLE_EMPLEADOS AS
SELECT A.EMPLOYEE_ID, A.FIRST_NAME||' '||A.LAST_NAME AS NAME, A.SALARY,
      B.JOB_TITLE, B.MIN_SALARY, B.MAX_SALARY,
      C.FIRST_NAME||' '||C.LAST_NAME AS MANAGER_NAME,
      D.FIRST_NAME||' '||D.LAST_NAME AS MANAGER_OF_MANAGER_NAME,
      E.DEPARTMENT_NAME,E.MANAGER_ID,
      F.FIRST_NAME||' '||F.LAST_NAME AS DEPARTMENT_MANAGER, 
      G.CITY, G.COUNTRY_ID,
      H.COUNTRY_NAME,
      I.REGION_NAME
      --J.JOB_ID
FROM EMPLOYEES A
INNER JOIN JOBS B
ON (A.JOB_ID = B.JOB_ID)
LEFT JOIN EMPLOYEES C
ON (A.MANAGER_ID = C.EMPLOYEE_ID)
LEFT JOIN EMPLOYEES D
ON (C.MANAGER_ID = D.EMPLOYEE_ID)
LEFT JOIN DEPARTMENTS E
ON (A.DEPARTMENT_ID = E.DEPARTMENT_ID)
LEFT JOIN EMPLOYEES F
ON (E.MANAGER_ID = F.EMPLOYEE_ID)
LEFT JOIN LOCATIONS G 
ON (E.LOCATION_ID = G.LOCATION_ID)
LEFT JOIN COUNTRIES H
ON (G.COUNTRY_ID = H.COUNTRY_ID)
LEFT JOIN REGIONS I
ON (H.REGION_ID = I.REGION_ID)
--LEFT JOIN JOB_HISTORY J
--ON (A.EMPLOYEE_ID = J.EMPLOYEE_ID)
ORDER BY A.EMPLOYEE_ID;



SELECT COUNT(1) CANTIDAD_REGISTRO, 
      SUM(SALARY) SALARIO_TOTAL, 
      AVG(SALARY) SALARIO_PROMEDIO,
      MAX(SALARY),MIN(SALARY)
      
FROM EMPLOYEES;


SELECT * 
FROM EMPLOYEES 
WHERE SALARY IN (24000,2100);




SELECT FIRST_NAME, 'POLLO'
FROM EMPLOYEES;


select * 
from VW_DETALLE_EMPLEADOS

;



SELECT NVL(B.DEPARTMENT_NAME,'SIN DEPARTAMENTO') AS DEPARTMENT_NAME, 
        SUM(SALARY) AS TOTAL_SALARY 
FROM EMPLOYEES A
LEFT JOIN DEPARTMENTS B
ON (A.DEPARTMENT_ID = B.DEPARTMENT_ID)
GROUP BY NVL(B.DEPARTMENT_NAME,'SIN DEPARTAMENTO')
ORDER BY TOTAL_SALARY; 

SELECT NVL(B.DEPARTMENT_NAME,'SIN DEPARTAMENTO') AS DEPARTMENT_NAME, 
        SUM(SALARY) AS TOTAL_SALARY 
FROM EMPLOYEES A, DEPARTMENTS B
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID(+)
GROUP BY NVL(B.DEPARTMENT_NAME,'SIN DEPARTAMENTO')
ORDER BY TOTAL_SALARY; 


--Para aplicar filtros de campos que son resultados de funciones de agregacion no se puede utilizar where
--en vez de ello se utiliza la sentencia having.
SELECT  NVL(D.COUNTRY_NAME,'SIN PAIS') AS COUNTRY_NAME, 
        NVL(B.DEPARTMENT_NAME,'SIN DEPARTAMENTO') AS DEPARTMENT_NAME, 
        SUM(SALARY) AS TOTAL_SALARY 
FROM EMPLOYEES A
LEFT JOIN DEPARTMENTS B
ON (A.DEPARTMENT_ID = B.DEPARTMENT_ID)
LEFT JOIN LOCATIONS C
ON (B.LOCATION_ID = C.LOCATION_ID)
LEFT JOIN COUNTRIES D
ON (C.COUNTRY_ID = D.COUNTRY_ID)
WHERE B.DEPARTMENT_NAME <> 'IT'
GROUP BY NVL(B.DEPARTMENT_NAME,'SIN DEPARTAMENTO'), NVL(D.COUNTRY_NAME,'SIN PAIS')
HAVING SUM(SALARY) > 20000
ORDER BY  3 ASC;  





SELECT CONCAT('QUE ', 'ONDAS') FROM DUAL;

SELECT UPPER(FIRST_NAME||' '||LAST_NAME) NOMBRE_MAYUSCULA, 
      LOWER(FIRST_NAME||' '||LAST_NAME) AS NOMBRE_MINUSCULA
FROM EMPLOYEES A;



INSERT INTO TABLA(NOMBRE) VALUES (INITCAP(:VARIABLE));



SELECT RPAD('1',5,'0') FROM DUAL;



 SELECT INITCAP( TRIM('   juan perez ')) FROM DUAL;





SELECT *
FROM EMPLOYEES 
WHERE DEPARTMENT_ID NOT IN (SELECT DEPARTMENT_ID FROM DEPARTMENTS);


SELECT *
FROM EMPLOYEES 
WHERE EMPLOYEE_ID NOT IN (SELECT EMPLOYEE_ID FROM JOB_HISTORY);


SELECT *
FROM JOB_HISTORY
WHERE EMPLOYEE_ID IN (103,104,105,106);


WITH EMPLOYEES_JOB_HISTORY AS (
  SELECT EMPLOYEE_ID FROM JOB_HISTORY
)
SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID NOT IN (SELECT EMPLOYEE_ID FROM EMPLOYEES_JOB_HISTORY);

--Calcular el porcentaje del salario de cada empleado con respecto al salario total de cada departamento



SELECT B.DEPARTMENT_ID,B.DEPARTMENT_NAME, SUM(SALARY) DEPARTMENT_SALARY
FROM EMPLOYEES A
LEFT JOIN DEPARTMENTS B
ON (A.DEPARTMENT_ID = B.DEPARTMENT_ID)
GROUP BY B.DEPARTMENT_ID, B.DEPARTMENT_NAME;


SELECT DEPARTMENT_ID, FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES;

--SUELDO_X_EMPLEADO/SALARIO_TOTAL_X_DEPARTAMENTO
SELECT A.DEPARTMENT_ID, A.FIRST_NAME||' '||LAST_NAME AS NAME,
      A.SALARY,B.DEPARTMENT_SALARY,
      ROUND((A.SALARY/B.DEPARTMENT_SALARY)*100,2) || '%' PERCENTAGE
FROM EMPLOYEES A
LEFT JOIN (
  SELECT B.DEPARTMENT_ID,B.DEPARTMENT_NAME, SUM(SALARY) DEPARTMENT_SALARY
  FROM EMPLOYEES A
  LEFT JOIN DEPARTMENTS B
  ON (A.DEPARTMENT_ID = B.DEPARTMENT_ID)
  GROUP BY B.DEPARTMENT_ID, B.DEPARTMENT_NAME
) B
ON (A.DEPARTMENT_ID = B.DEPARTMENT_ID)
ORDER BY A.DEPARTMENT_ID;


---LA MISMA CONSULTA ANTERIOR UTILIZANDO WITH
WITH DEPARTMENTS_SALARIES AS (
  SELECT B.DEPARTMENT_ID,B.DEPARTMENT_NAME, SUM(SALARY) DEPARTMENT_SALARY
  FROM EMPLOYEES A
  LEFT JOIN DEPARTMENTS B
  ON (A.DEPARTMENT_ID = B.DEPARTMENT_ID)
  GROUP BY B.DEPARTMENT_ID, B.DEPARTMENT_NAME
)
SELECT A.DEPARTMENT_ID, A.FIRST_NAME||' '||LAST_NAME AS NAME,
      A.SALARY,B.DEPARTMENT_SALARY,
      ROUND((A.SALARY/B.DEPARTMENT_SALARY)*100,2) || '%' PERCENTAGE
FROM EMPLOYEES A
LEFT JOIN DEPARTMENTS_SALARIES B
ON (A.DEPARTMENT_ID = B.DEPARTMENT_ID)
ORDER BY A.DEPARTMENT_ID;




SELECT * 
FROM (SELECT * FROM EMPLOYEES);
